remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Sourbh Choudhary]
description: [QA Automation Engineer (SDET) | Selenium | API | Java | SQL | HIPAA]
